FROM node:20-alpine AS deps
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN corepack enable && pnpm install --frozen-lockfile

FROM node:20-alpine AS builder
WORKDIR /app

# NEXT_PUBLIC_* env vars are inlined into the JS bundle at build time and
# baked into prerendered static pages, so they MUST be present during
# `pnpm build`. Dokploy injects environment variables into the build
# container via build args; declaring them here propagates each one into
# the build's process.env where Next.js can pick it up.

# Site
ARG NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}

# Umami analytics
ARG NEXT_PUBLIC_UMAMI_WEBSITE_ID
ENV NEXT_PUBLIC_UMAMI_WEBSITE_ID=${NEXT_PUBLIC_UMAMI_WEBSITE_ID}
ARG NEXT_PUBLIC_UMAMI_HOST
ENV NEXT_PUBLIC_UMAMI_HOST=${NEXT_PUBLIC_UMAMI_HOST}

# Google AdSense (client ID has a default in code; slot IDs do not)
ARG NEXT_PUBLIC_ADSENSE_CLIENT_ID
ENV NEXT_PUBLIC_ADSENSE_CLIENT_ID=${NEXT_PUBLIC_ADSENSE_CLIENT_ID}
ARG NEXT_PUBLIC_ADSENSE_SLOT_MID
ENV NEXT_PUBLIC_ADSENSE_SLOT_MID=${NEXT_PUBLIC_ADSENSE_SLOT_MID}
ARG NEXT_PUBLIC_ADSENSE_SLOT_FOOTER
ENV NEXT_PUBLIC_ADSENSE_SLOT_FOOTER=${NEXT_PUBLIC_ADSENSE_SLOT_FOOTER}

# Registrar referral codes — rendered into client-side outbound links
ARG NEXT_PUBLIC_HOSTINGER_REF
ENV NEXT_PUBLIC_HOSTINGER_REF=${NEXT_PUBLIC_HOSTINGER_REF}
ARG NEXT_PUBLIC_PORKBUN_REF
ENV NEXT_PUBLIC_PORKBUN_REF=${NEXT_PUBLIC_PORKBUN_REF}
ARG NEXT_PUBLIC_NAMECHEAP_AFF
ENV NEXT_PUBLIC_NAMECHEAP_AFF=${NEXT_PUBLIC_NAMECHEAP_AFF}
ARG NEXT_PUBLIC_GODADDY_AFF
ENV NEXT_PUBLIC_GODADDY_AFF=${NEXT_PUBLIC_GODADDY_AFF}
ARG NEXT_PUBLIC_DYNADOT_REF
ENV NEXT_PUBLIC_DYNADOT_REF=${NEXT_PUBLIC_DYNADOT_REF}
ARG NEXT_PUBLIC_NAMESILO_RID
ENV NEXT_PUBLIC_NAMESILO_RID=${NEXT_PUBLIC_NAMESILO_RID}
ARG NEXT_PUBLIC_IONOS_AFF
ENV NEXT_PUBLIC_IONOS_AFF=${NEXT_PUBLIC_IONOS_AFF}
ARG NEXT_PUBLIC_SPACESHIP_REF
ENV NEXT_PUBLIC_SPACESHIP_REF=${NEXT_PUBLIC_SPACESHIP_REF}
ARG NEXT_PUBLIC_NAMECOM_AFF
ENV NEXT_PUBLIC_NAMECOM_AFF=${NEXT_PUBLIC_NAMECOM_AFF}
ARG NEXT_PUBLIC_HOVER_REF
ENV NEXT_PUBLIC_HOVER_REF=${NEXT_PUBLIC_HOVER_REF}
ARG NEXT_PUBLIC_DREAMHOST_REF
ENV NEXT_PUBLIC_DREAMHOST_REF=${NEXT_PUBLIC_DREAMHOST_REF}
ARG NEXT_PUBLIC_HOSTGATOR_AFF
ENV NEXT_PUBLIC_HOSTGATOR_AFF=${NEXT_PUBLIC_HOSTGATOR_AFF}

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN corepack enable && pnpm build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
RUN addgroup --system --gid 1001 nodejs && adduser --system --uid 1001 nextjs
COPY --from=builder /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
USER nextjs
EXPOSE 3000
ENV PORT=3000 HOSTNAME=0.0.0.0
CMD ["node", "server.js"]
